### ISSUE TITLE
MPLS packet not correctly parsed.

### ISSUE THREAD

**Issue by nickkaranatsios** [trema/trema-edge#19]
Sending an MPLS packet which contains no IPv4 information the packet_parser asserts and aborts.

**Comment by kazuyas** [comment]
I will prepare the MPLS packet with correct IPv4 information.

**Comment by kazuyas** [comment]
My previous comment is a misunderstanding. Please ignore it.

We discussed the problem for mpls packet parsing and concluded that trema parses only ethernet and mpls header but l3 header when trema received a mpls packet.
