### ISSUE TITLE
Multiple table usage error

### ISSUE THREAD

**Issue by miyahirodazu** [trema/trema-edge#39]
Hi there,

I have tried to use multiple tables with trema-edge base controller with trema-edge switch.
When I specify goto table  instruction in table 0 which specifies table 1 as the destination table.
However, I got error message as below.

Goto table from 0 to 0 is not allowed.
Failed to apply instructions ( ret = 1 ).

Actually, I have specified table1 in table0, so the message seems strange.

Thanks for your help.

**Comment by hkwi** [comment]
With trema-edge switch, I could put the instruction of GOTO_TABLE, table_id=1 in the FLOW_MOD table_id=0 message. So it seems that the controller have some problem.

**Comment by miyahirodazu** [comment]
Thanks hkwi, I try with the latest version of trema-edge switch, it works. (with the same controller).
It has been fixed.
