### ISSUE TITLE
LoggerモジュールがSinatraと衝突して動かない

### ISSUE THREAD

**Issue by proshiba** [trema/trema-edge#54]
RESTAPIを搭載したく、Sinatraと動かそうとしました。
その結果、trema-edgeとsinatraを使ってみようとしたところ、webアクセスをしようとすると以下のエラーが出ました。
Logger is not a class
※　ブラウザ上は、504 internal error　になっていました

恐らく、trema-edgeではまだLogger用のモジュールがDefaultLoggerではなく、Loggerであるため、ぶつかったんだと思われます。
(sinatraのloggerがRac::CommonLogger のLoggerクラスであるため、これがtremaのLoggerモジュールとぶつかった)
trema のmodule名をTremaLoggerにしたところ、問題なくsinatraでWebアクセスできました。
（とりあえず、dpidのArrayを画面表示させるところまで出来ることを確認）
※　logger.cの内容とlogger.rb、controller.rbの内容を変更しています。(*.cも変えてますので、最後にrakeしてます。)

logger.c
mLogger = rb_define_module_under( mTrema, "Logger" ); //変更前
mLogger = rb_define_module_under( mTrema, "TremaLogger" ); //変更後

logger.rb
module Logger # 変更前
module TremaLogger # 変更後

Controller.rb
include Logger # 変更前
include TremaLogger # 変更後

※　ちなみにDefaultLoggerじゃなく、TremaLoggerにしたのは、絶対ぶつからないようにしたかったからです。

**Comment by yasuhito** [comment]
@proshiba こちらも修正しました。遅くなってすみません。。
