### ISSUE TITLE
Write-Action instruction does not allow to modify multiple header fields

### ISSUE THREAD

**Issue by chibacchie** [trema/trema-edge#86]
writeインストラクションのactionリストに複数のフィールドに対するset_fieldを
指定した場合、list中の最後に現れるset_fieldしか実行されない。

OF1.3.3の仕様上、writeインストラクションで書き換えを行うaction setには
各アクションは一つずつしか存在できないが、set_fieldアクションに関しては
書き換え対象のフィールドが異なれば、action set上に複数存在できる
（OF1.3.3 pp.24）。

例) flow modの内容が下記の場合、eth_srcは01:23:45:67:89:00にならず、
    eth_dstのみeth_dst:01:23:44:55:66:77になる。
  flow_mod cmd=add \
    table_id=0 prio=100 \
    write: set_field=eth_src:01:23:45:67:89:00 \
           set_field=eth_dst:01:23:44:55:66:77 \
           output=1

**Comment by iHiroakiKawai** [comment]
unit test も作らないとですね…。
